In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
print(a)

[1 2 3 4 5 6 7 8]


In [7]:
mp=np.array([[1,2,3],[1,2,3]])
print(mp)

[[1 2 3]
 [1 2 3]]


mp.shape

In [8]:
mp.shape

(2, 3)

In [15]:
s="Hello World,bye"
st=np.array(s)
print(st)

Hello World,bye


In [16]:
st

array('Hello World,bye', dtype='<U15')

In [17]:
print(a[3:6])

[4 5 6]


In [18]:
print(a[:-3])

[1 2 3 4 5]


In [19]:
print(mp[:,1:2])

[[2]
 [2]]


In [24]:
print(mp[:,-1])

[3 3]


In [26]:
x=[i for i in range(0,5)]
print(x)
print("out of loop")

[0, 1, 2, 3, 4]
out of loop


In [27]:
import pandas as pd

In [30]:
s=pd.Series(x)
print(s)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [32]:
print(pd.Series(x,index=[1,2,3,4,5]))

1    0
2    1
3    2
4    3
5    4
dtype: int64


In [34]:
se=pd.Series(a)

In [36]:
print(se[2:5])

2    3
3    4
4    5
dtype: int32


In [40]:
df=pd.DataFrame(mp)
print(df)

   0  1  2
0  1  2  3
1  1  2  3


In [41]:
lt=[["ananya",200],['rishabh',201]]
l=pd.DataFrame(lt)

In [42]:
l

0    1
0   ananya  200
1  rishabh  201

In [43]:
data={'name':['suraj','panda','choti','zehr'],'age':[20,20,20,32]}
ld=pd.DataFrame(data)

In [44]:
ld

name  age
0  suraj   20
1  panda   20
2  choti   20
3   zehr   32

In [54]:
data={'name':['suraj','panda','choti','zehr'],'age':[20,20,20,32]}
ld=pd.DataFrame(data,index=[1,2,3,4])

In [55]:
ld

name  age
1  suraj   20
2  panda   20
3  choti   20
4   zehr   32

In [56]:
ld.to_csv('friend.csv')

In [57]:
z=pd.read_csv('friend.csv')
print(z)

   Unnamed: 0   name  age
0           1  suraj   20
1           2  panda   20
2           3  choti   20
3           4   zehr   32


In [58]:
z.iloc[:,1:]

name  age
0  suraj   20
1  panda   20
2  choti   20
3   zehr   32

In [160]:
dic={'sky':['Sunny','Sunny','Rainy','Sunny'],'Air Temp':['Warm','Warm','Cold','Warm'],'Humid':['Normal','High','High','High'],'Wind':['Strong','Strong','Strong','Strong'],'water':['warm','warm','warm','Cold'],'Forecast':['Same','Same','Change','Change'],'Enjoy Sport':['Yes','Yes','No','Yes']}

In [161]:
data=pd.DataFrame(dic)

In [162]:
data

sky Air Temp   Humid    Wind water Forecast Enjoy Sport
0  Sunny     Warm  Normal  Strong  warm     Same         Yes
1  Sunny     Warm    High  Strong  warm     Same         Yes
2  Rainy     Cold    High  Strong  warm   Change          No
3  Sunny     Warm    High  Strong  Cold   Change         Yes

In [163]:
data.to_csv('weather.csv')

In [164]:
data1=pd.read_csv('weather.csv')

In [165]:
data1=data1.iloc[:,1:]

In [168]:
data1.iloc[0,-1]

'Yes'

In [169]:
h=['0','0','0','0','0','0']
for i in range(4):
    for j in range(6):
        if(data1.iloc[i,-1]=='Yes'):
            if(i==0):
                h=data1.iloc[0,:-1].values
            else:
                if(h[j]!=data1.iloc[i,j] and h[j]!='?'):
                      h[j]='?'
    print(h)


['Sunny' 'Warm' 'Normal' 'Strong' 'warm' 'Same']
['Sunny' 'Warm' '?' 'Strong' 'warm' 'Same']
['Sunny' 'Warm' '?' 'Strong' 'warm' 'Same']
['Sunny' 'Warm' '?' 'Strong' '?' '?']
