In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("preprocessing.csv")

In [4]:
data

Country State   Age   Salary Purchased
0   france     A  44.0  72000.0        no
1    spain     B  27.0  48000.0       yes
2  germany     B  30.0  54000.0        no
3    spain     A  38.0  61000.0        no
4  germany     C  40.0      NaN       yes
5   france     C  35.0  58000.0       yes
6    spain     B   NaN  52000.0        no
7   france     A  48.0  79000.0       yes
8  germany     C  50.0  83000.0        no
9   france     B  37.0  67000.0       yes

In [6]:
x=data.iloc[:,:-1].values

In [7]:
y=data.iloc[:,-1].values

In [11]:
from sklearn.preprocessing import Imputer 

In [13]:
imputer=Imputer(missing_values="NaN",strategy='mean',axis=0)
imputer=imputer.fit(x[:,2:4])

In [14]:
x[:,2:4]=imputer.transform(x[:,2:4])

In [15]:
x

array([['france', 'A', 44.0, 72000.0],
       ['spain', 'B', 27.0, 48000.0],
       ['germany', 'B', 30.0, 54000.0],
       ['spain', 'A', 38.0, 61000.0],
       ['germany', 'C', 40.0, 63777.77777777778],
       ['france', 'C', 35.0, 58000.0],
       ['spain', 'B', 38.77777777777778, 52000.0],
       ['france', 'A', 48.0, 79000.0],
       ['germany', 'C', 50.0, 83000.0],
       ['france', 'B', 37.0, 67000.0]], dtype=object)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.20,random_state=0)

In [18]:
train_x

array([['germany', 'C', 40.0, 63777.77777777778],
       ['france', 'B', 37.0, 67000.0],
       ['spain', 'B', 27.0, 48000.0],
       ['spain', 'B', 38.77777777777778, 52000.0],
       ['france', 'A', 48.0, 79000.0],
       ['spain', 'A', 38.0, 61000.0],
       ['france', 'A', 44.0, 72000.0],
       ['france', 'C', 35.0, 58000.0]], dtype=object)

In [19]:
test_x

array([['germany', 'B', 30.0, 54000.0],
       ['germany', 'C', 50.0, 83000.0]], dtype=object)

In [20]:
train_y

array(['yes', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'yes'], dtype=object)

In [21]:
test_y

array(['no', 'no'], dtype=object)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
sc=StandardScaler()
train_x[:,2:4]=sc.fit_transform(train_x[:,2:4])

In [24]:
test_x[:,2:4]=sc.fit_transform(test_x[:,2:4])

In [25]:
test_x

array([['germany', 'B', -1.0, -1.0],
       ['germany', 'C', 1.0, 1.0]], dtype=object)

In [26]:
train_x

array([['germany', 'C', 0.2630675731713538, 0.1238147854838185],
       ['france', 'B', -0.25350147960148617, 0.4617563176278856],
       ['spain', 'B', -1.9753983221776195, -1.5309334063940294],
       ['spain', 'B', 0.05261351463427101, -1.1114197802841526],
       ['france', 'A', 1.6405850472322605, 1.7202971959575162],
       ['spain', 'A', -0.08131179534387283, -0.16751412153692966],
       ['france', 'A', 0.9518263102018072, 0.9861483502652316],
       ['france', 'C', -0.5978808481167128, -0.48214934111933727]],
      dtype=object)

In [27]:
social=pd.read_csv("Social.csv")

In [28]:
x=social.iloc[:,:-1].values

In [29]:
y=social.iloc[:,-1].values

In [30]:
x

array([[15624510,        0,       19,    19000],
       [15810944,        0,       35,    20000],
       [15668575,        1,       26,    43000],
       ...,
       [15654296,        1,       50,    20000],
       [15755018,        0,       36,    33000],
       [15594041,        1,       49,    36000]], dtype=int64)

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [32]:
socialx_train,socialx_test,socialy_train,socialy_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [33]:
socialx_train

array([[15664907,        0,       58,   144000],
       [15605000,        1,       59,    83000],
       [15649136,        1,       24,    55000],
       ...,
       [15591433,        0,       36,    52000],
       [15776348,        1,       27,    54000],
       [15794661,        1,       26,   118000]], dtype=int64)

In [34]:
socialx_test

array([[15725660,        0,       30,    87000],
       [15652400,        1,       38,    50000],
       [15776844,        0,       35,    75000],
       [15738448,        1,       30,    79000],
       [15638003,        1,       35,    50000],
       [15814004,        0,       27,    20000],
       [15610140,        1,       31,    15000],
       [15680587,        0,       36,   144000],
       [15666141,        1,       18,    68000],
       [15622478,        0,       47,    43000],
       [15689425,        0,       30,    49000],
       [15800061,        1,       28,    55000],
       [15773447,        0,       37,    55000],
       [15579212,        0,       39,    77000],
       [15746139,        0,       20,    86000],
       [15789109,        1,       32,   117000],
       [15760570,        0,       37,    77000],
       [15807909,        0,       19,    85000],
       [15654230,        1,       55,   130000],
       [15708228,        0,       35,    22000],
       [15609653,   

In [35]:
socialx_train[:,2:4]=sc.fit_transform(socialx_train[:,2:4])

In [36]:
socialx_test[:,2:4]=sc.fit_transform(socialx_test[:,2:4])

In [38]:
socialx_train

array([[15664907,        0,        1,        2],
       [15605000,        1,        2,        0],
       [15649136,        1,       -1,        0],
       ...,
       [15591433,        0,        0,        0],
       [15776348,        1,       -1,        0],
       [15794661,        1,       -1,        1]], dtype=int64)

In [39]:
socialx_test

array([[15725660,        0,        0,        0],
       [15652400,        1,        0,        0],
       [15776844,        0,        0,        0],
       [15738448,        1,        0,        0],
       [15638003,        1,        0,        0],
       [15814004,        0,        0,       -1],
       [15610140,        1,        0,       -1],
       [15680587,        0,        0,        2],
       [15666141,        1,       -1,        0],
       [15622478,        0,        1,        0],
       [15689425,        0,        0,        0],
       [15800061,        1,        0,        0],
       [15773447,        0,        0,        0],
       [15579212,        0,        0,        0],
       [15746139,        0,       -1,        0],
       [15789109,        1,        0,        1],
       [15760570,        0,        0,        0],
       [15807909,        0,       -1,        0],
       [15654230,        1,        1,        1],
       [15708228,        0,        0,       -1],
       [15609653,   

In [41]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)

In [44]:
classifier.fit(socialx_train,socialy_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [48]:
pred=classifier.predict(socialx_test)
pred

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int64)

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(socialy_test,pred)

In [47]:
cm

array([[46, 12],
       [ 4, 18]], dtype=int64)